#!/usr/bin/env bash
#MISE description="Remove a worktree"
#USAGE arg "<worktree>" help="The git worktree to remove"
#USAGE complete "worktree" run="../.scripts/list-worktrees.sh"

# Note: The "run" script path is relative to the project root
./.scripts/remove-worktree.sh "$1"
