#!/usr/bin/env bash
# Write <worktree>/.units.env, the per-worktree values the Quadlet templates read.
#
# Quadlet does not expand shell variables in unit keys, but systemd DOES expand
# ${VAR} in the generated ExecStart from an EnvironmentFile=. So everything that
# varies per worktree -- ports derived from WORKTREE_ID, the routed hostnames,
# the version-keyed image tags -- reaches the units through this file rather
# than through the templates, which stay identical for every worktree.
#
# Run from inside a worktree, so mise has loaded that worktree's env. Rerun it
# after anything that changes those values: a .ruby-version or .nvmrc bump, a
# Gemfile.lock Playwright bump, or a new WORKTREE_ID.
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

: "${PROJECT_PREFIX:?run from a worktree directory (mise env not loaded)}"
: "${CURRENT_WORKTREE_NAME:?CURRENT_WORKTREE_NAME unset (mise env not loaded)}"

OUT="$PWD/.units.env"

# An unset variable expands to an empty string in ExecStart, and podman then
# does something quietly wrong rather than failing -- `--publish 127.0.0.1::5432`
# picks a random host port, `--cpus=` is rejected only sometimes. So every value
# is required, and a missing one is a hard error here where it is visible.
REQUIRED=(
  WORKTREE_ID WORKTREE_HOST S3_HOST RUSTFS_UI_HOST
  DB_PORT RUBY_DEBUG_PORT NVIM_PORT PLAYWRIGHT_HOST_PORT
  GEM_VOLUME MAIN_WORKTREE_PATH RUBY_VERSION NODE_VERSION
  SSH_PATH SSH_AGENT_SOCK NVIM_CONFIG_DIR
  CPUS_25 CPUS_50 CPUS_75 PGPASSWORD
)
missing=()
for v in "${REQUIRED[@]}"; do
  [[ -n "${!v:-}" ]] || missing+=("$v")
done
if (( ${#missing[@]} )); then
  printf 'error: these are unset in this worktree'\''s mise env:\n' >&2
  printf '  %s\n' "${missing[@]}" >&2
  printf '\nIs mise.local.toml present in this worktree? It is rendered by\n' >&2
  printf 'create-worktree.sh from .mise/local.toml.template.\n' >&2
  exit 1
fi

# Empty PLAYWRIGHT_VERSION means Gemfile.lock could not be parsed; fall back to
# the same default the compose file used, and say so.
pw="${PLAYWRIGHT_VERSION:-}"
if [[ -z "$pw" ]]; then
  pw=1.60.0
  printf 'warn: PLAYWRIGHT_VERSION is empty (stale mise.local.toml?), using %s\n' "$pw" >&2
fi

{
  printf '# Generated by .scripts/units-env.sh -- do not edit.\n'
  printf '# Regenerate after a ruby/node/playwright bump: mise run podman:env\n\n'

  printf 'WORKTREE_HOST=%s\n'         "$WORKTREE_HOST"
  printf 'S3_HOST=%s\n'               "$S3_HOST"
  printf 'RUSTFS_UI_HOST=%s\n'        "$RUSTFS_UI_HOST"
  printf 'PODMAN_TRAEFIK_IP=%s\n'     "${PODMAN_TRAEFIK_IP:-10.214.0.2}"
  printf '\n'
  printf 'DB_PORT=%s\n'               "$DB_PORT"
  printf 'RUBY_DEBUG_PORT=%s\n'       "$RUBY_DEBUG_PORT"
  printf 'NVIM_PORT=%s\n'             "$NVIM_PORT"
  printf 'PLAYWRIGHT_HOST_PORT=%s\n'  "$PLAYWRIGHT_HOST_PORT"
  printf '\n'
  # Shared tag keyed by runtime versions, so one image serves every worktree on
  # the same combination instead of one per project.
  printf 'RAILS_IMAGE=localhost/%s/rails:ruby%s-node%s\n'      "$PROJECT_PREFIX" "$RUBY_VERSION" "$NODE_VERSION"
  printf 'NVIM_IMAGE=localhost/%s/nvim:ruby%s-node%s\n'        "$PROJECT_PREFIX" "$RUBY_VERSION" "$NODE_VERSION"
  printf 'PLAYWRIGHT_IMAGE=localhost/%s/playwright:v%s\n'      "$PROJECT_PREFIX" "$pw"
  printf 'CLAUDE_IMAGE=localhost/%s/claude:latest\n'           "$PROJECT_PREFIX"
  printf '\n'
  printf 'GEM_VOLUME=%s\n'            "$GEM_VOLUME"
  printf 'MAIN_WORKTREE_PATH=%s\n'    "$MAIN_WORKTREE_PATH"
  printf 'NVIM_CONFIG_DIR=%s\n'       "$NVIM_CONFIG_DIR"
  printf 'SSH_PATH=%s\n'              "$SSH_PATH"
  printf 'SSH_AGENT_SOCK=%s\n'        "$SSH_AGENT_SOCK"
  printf '\n'
  printf 'CPUS_25=%s\n'               "$CPUS_25"
  printf 'CPUS_50=%s\n'               "$CPUS_50"
  printf 'CPUS_75=%s\n'               "$CPUS_75"
  printf '\n'
  # db@ takes no shared .env (that file sets PGHOST=db and breaks initdb), so
  # its password comes from here.
  printf 'POSTGRES_PASSWORD=%s\n'     "$PGPASSWORD"
  printf 'HEADLESS_SYSTEM_TESTS=%s\n' "${HEADLESS_SYSTEM_TESTS:-0}"
} > "$OUT"

printf 'Wrote %s\n' "$OUT"
printf '  worktree %s (id %s) -> http://%s\n' "$CURRENT_WORKTREE_NAME" "$WORKTREE_ID" "$WORKTREE_HOST"
printf '  db 127.0.0.1:%s   nvim :%s   playwright :%s   ruby-debug :%s\n' \
  "$DB_PORT" "$NVIM_PORT" "$PLAYWRIGHT_HOST_PORT" "$RUBY_DEBUG_PORT"
